## Ansible file for checking which version of Git is installed, and updating it if necesary
# indentation: 2 spaces

---
- name: Update Git
  hosts: all
  gather_facts: true

  vars:
    updated_servers: []
  tasks:

  - name: Check version of Git on Ubuntu servers
    command: git --version
    when: ansible_os_family == "Debian"
    register: git_version
    changed_when: false

  - name: Check version of Git on RedHat servers
    command: git --version
    when: ansible_os_family == "RedHat"
    register: git_version
    changed_when: false
#  - name: Update Git on Ubuntu servers
#    apt:
#      name: git
#      state: latest
#    when: ansible_os_family == "Debian"
#    register: git_update
#    notify:
#      - restart git

#  - name: Update Git on RedHat servers
#    yum:
#      name: git
#      state: latest
#    when: ansible_os_family == "RedHat"
#    register: git_update
#    notify:
#      - restart git

#  - name: Append to updated servers list
#    set_fact:
#      updated_servers: "{{ updated_servers + [ ansible_host ] }}"
#    when: git_update.changed

  - name: Print Git version
    debug:
      msg: "Git version is {{ git_version.stdout }}"

  - name: Print list of servers with updated Git version
    debug:
      msg: "The following servers had their Git version updated: {{ updated_servers }}"

  handlers:
    - name: restart git
      service:
        name: git
        state: restarted
