## Ansible file for rebooting a server
# indentation: 2 spaces

---
- name: Reboot server ONLY USE WITH LIMIT
  hosts: all
  tasks:
    - name: Reboot linux server
      shell: sudo -n reboot

    - name: wait for the system to come back
      wait_for_connection: