## Ansible file for rebooting a server
# indentation: 2 spaces

---
- name: Reboot server ONLY USE WITH LIMIT
  hosts: all
  tasks:
    - name: Reboot linux server
    - reboot: null
      msg: Reboot initiated by Ansible
      post_reboot_delay: 30
      test_command: uptime