## Ansible file for rebooting a server
# indentation: 2 spaces

---
- name: Reboot server ONLY USE WITH LIMIT
  hosts: all
  tasks:
    - name: Wait for user confirmation
      pause:
        seconds: 300
        prompt: "Press ctrl+c to continue or wait 300 seconds - DID YOU REMEMBER TO USE LIMIT?"

    - name: Reboot Debian based servers
      reboot:
      when: ansible_facts['os_family'] == "Debian"

    - name: Reboot RedHat based servers
      ansible.builtin.reboot:
      when: ansible_facts['os_family'] == "RedHat"